/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export const enum EmbeddingModel {
  AllMiniLML6V2 = 0,
  BGEBaseENV15 = 1,
  BGELargeENV15 = 2,
  BGESmallENV15 = 3,
  NomicEmbedTextV1 = 4,
  ParaphraseMLMiniLML12V2 = 5
}
export type JsTextEmbedding = TextEmbedding
export class TextEmbedding {
  constructor(model?: EmbeddingModel | undefined | null, cacheDir?: string | undefined | null, maxLength?: number | undefined | null, showDownloadProgress?: boolean | undefined | null)
  embed(texts: Array<string>, batchSize?: number | undefined | null): Array<Array<number>>
}
